import json
import subprocess
import os
from datetime import datetime
from dotenv import load_dotenv

# Load environment variables
load_dotenv(os.path.join(os.path.dirname(__file__), '..', '.env'))

from db_utils import run_team_db

        return json.loads(result.stdout)
    except Exception as e:
        print(f"Error: {e}")
        return []

def get_sector_social_data(category):
    cats = [category]
    if category.lower() == 'climate tech':
        cats = ['climate', 'Climate Tech', 'ClimateTech']
    elif category.lower() == 'ai':
        cats = ['ai', 'AI']
    elif category.lower() == 'biotech':
        cats = ['biotech', 'Biotech']
    
    cat_filter = " OR ".join([f"category = '{c}'" for c in cats])
    
    sql = f"""
    SELECT source, title, sentiment, importance 
    FROM signals 
    WHERE source IN ('reddit', 'hackernews', 'producthunt', 'Twitter') 
    AND ({cat_filter})
    AND sentiment != ''
    ORDER BY timestamp DESC
    LIMIT 10
    """
    return run_team_db(sql)

def generate_report():
    sectors = [
        {"name": "AI", "reddit": "r/MachineLearning", "hn": "AI"},
        {"name": "Climate Tech", "reddit": "r/ClimateTech", "hn": "Energy"},
        {"name": "Biotech", "reddit": "r/biotech", "hn": "Biotech"},
        {"name": "SpaceTech", "reddit": "r/spacex", "hn": "Space"},
        {"name": "DefenseTech", "reddit": "r/DefenseTech", "hn": "Defense"},
        {"name": "Longevity", "reddit": "r/longevity", "hn": "Health"}
    ]
    
    full_report = f"# 🌐 NichePulse Community Pulse - {datetime.now().strftime('%B %d, %Y')}

"
    full_report += "Distilled community sentiment and emerging signals from Reddit, HN, and niche forums. 🧵👇

"
    
    for sector in sectors:
        name = sector['name']
        data = get_sector_social_data(name)
        
        pos_count = sum(1 for d in data if d['sentiment'] == 'Positive')
        neg_count = sum(1 for d in data if d['sentiment'] == 'Negative')
        
        overall = "Neutral ⚪"
        if pos_count > neg_count: overall = "Bullish 📈"
        elif neg_count > pos_count: overall = "Bearish 📉"
        
        hashtag = name.replace(" ", "")
        
        full_report += f"## #{hashtag} Pulse
"
        full_report += f"**Community Vibe:** {overall}

"
        
        if not data:
            full_report += "*Quiet on the community front today.*

"
        else:
            full_report += "### 💎 Top Signals
"
            for d in data[:5]:
                sentiment_icon = "🟢" if d['sentiment'] == 'Positive' else ("🔴" if d['sentiment'] == 'Negative' else "⚪")
                full_report += f"- {sentiment_icon} **{d['title']}**
"
            
            # Formatting for Reddit
            full_report += f"
#### 🚀 Reddit-Ready Post ({sector['reddit']})
"
            reddit_post = f"**{name} Community Pulse: {overall}**

"
            reddit_post += "Top signals we're tracking today:

"
            for d in data[:3]:
                sentiment_icon = "✅" if d['sentiment'] == 'Positive' else ("⚠️" if d['sentiment'] == 'Negative' else "ℹ️")
                reddit_post += f"* {sentiment_icon} {d['title']}
"
            reddit_post += f"
Generated by NichePulse AI. Get the full brief at [nichepulse.ai](http://localhost:3000)"
            full_report += f"```
{reddit_post}
```

"
            
        full_report += "---

"
        
    full_report += "### 🚀 Automated Intelligence for Busy Professionals
"
    full_report += "NichePulse distill thousands of signals into a 5-minute daily brief. Stay ahead of the curve without the noise.

"
    full_report += "🔗 [Join the waitlist](http://localhost:3000)

"
    full_report += "#AI #Biotech #ClimateTech #Space #DefenseTech #Longevity #Intelligence"
    
    return full_report

def main():
    report = generate_report()
    output_path = "/home/team/shared/growth/community_pulse_reports.md"
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    with open(output_path, "w") as f:
        f.write(report)
    
    print(f"Community Pulse Report generated at {output_path}")

if __name__ == "__main__":
    main()
