#!/usr/bin/env python3
"""
SEO Blog Generator for NichePulse.
Generates long-form, SEO-optimized blog posts from daily intelligence signals.
Archives to the `reports` database table (type='blog') for frontend display.
"""
import json
import subprocess
import uuid
from datetime import datetime, timedelta
import os
import sys
from openai import OpenAI
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv(os.path.join(os.path.dirname(__file__), '..', '.env'))

from db_utils import run_team_db

def get_stories_for_date(date_str):
    return run_team_db(f"SELECT * FROM stories WHERE created_at LIKE '{date_str}%'")

def get_daily_brief_for_date(date_str):
    briefs = run_team_db(f"SELECT content FROM reports WHERE date = '{date_str}' AND type = 'daily' LIMIT 1")
    if briefs:
        return briefs[0]['content']
    return None

def get_latest_story_date():
    result = run_team_db("SELECT MAX(created_at) as latest FROM stories")
    if result and result[0]['latest']:
        return result[0]['latest'][:10]
    return None

def generate_seo_blog(stories, daily_brief):
    if not stories:
        return None
        
    api_key = os.environ.get('OPENAI_API_KEY')
    if not api_key:
        print("OPENAI_API_KEY not found in environment. Using fallback template generation.")
        return generate_fallback_blog(stories)

    client = OpenAI(api_key=api_key)
    stories_text = json.dumps(stories, indent=2)
    
    # Load prompt template
    prompt_path = os.path.join(os.path.dirname(__file__), 'prompts', 'seo_blog.txt')
    if not os.path.exists(prompt_path):
        print(f"Prompt template not found at {prompt_path}, using fallback.")
        return generate_fallback_blog(stories)
        
    with open(prompt_path, 'r') as f:
        prompt_template = f.read()
    
    prompt = prompt_template.format(stories_text=stories_text)
    
    if daily_brief:
        prompt += f"\n\nReference the following Daily Brief summary for context, but expand significantly for the blog:\n{daily_brief}"

    try:
        response = client.chat.completions.create(
            model="gpt-4o",
            messages=[{"role": "system", "content": "You are a professional tech journalist and SEO specialist."},
                      {"role": "user", "content": prompt}]
        )
        blog_content = response.choices[0].message.content
        return blog_content
    except Exception as e:
        print(f"Error calling LLM for SEO blog generation: {e}")
        print("Falling back to template-based generation.")
        return generate_fallback_blog(stories)

def generate_fallback_blog(stories):
    """Generate a structured blog post from stories without needing an LLM API key."""
    if not stories:
        return None
    
    today = datetime.now().strftime('%B %d, %Y')
    sectors = {}
    for s in stories:
        cat = s.get('category', 'General')
        if cat not in sectors:
            sectors[cat] = []
        sectors[cat].append(s)
    
    lines = []
    lines.append(f"# NichePulse Daily Intelligence: {today}")
    lines.append("")
    lines.append(f"*Automated intelligence roundup for fast-moving professionals.*")
    lines.append("")
    lines.append("## Executive Summary")
    lines.append("")
    lines.append(f"Today's intelligence covers {len(stories)} key signals across {len(sectors)} sectors. "
                 "Stay ahead of the curve with NichePulse's AI-distilled market intelligence.")
    lines.append("")
    
    for sector, sector_stories in sectors.items():
        lines.append(f"## {sector} Sector")
        lines.append("")
        for s in sector_stories:
            title = s.get('title', 'Signal')
            summary = s.get('summary', '')
            lines.append(f"### {title}")
            if summary:
                lines.append(f"{summary}")
            lines.append("")
    
    lines.append("## Market Sentiment Analysis")
    lines.append("")
    lines.append("Market signals indicate a dynamic landscape with significant opportunities "
                 "across all tracked sectors. Key themes include technological advancement, "
                 "regulatory developments, and shifts in investment patterns.")
    lines.append("")
    lines.append("## Conclusion & Future Outlook")
    lines.append("")
    lines.append("Stay informed with NichePulse — your daily edge in high-growth industries. "
                 "Upgrade to Premium for deep-dive analysis and historical data exports.")
    lines.append("")
    lines.append("---")
    lines.append("*Generated by NichePulse AI Intelligence Pipeline*")
    
    return "\n".join(lines)

def main():
    # Allow passing date as argument YYYY-MM-DD
    target_date = None
    if len(sys.argv) > 1:
        target_date = sys.argv[1]
    else:
        # Try today
        today = datetime.now().strftime('%Y-%m-%d')
        stories = get_stories_for_date(today)
        if stories:
            target_date = today
        else:
            # Try latest available
            target_date = get_latest_story_date()
            
    if not target_date:
        print("No stories found in database.")
        return
        
    stories = get_stories_for_date(target_date)
    if not stories:
        print(f"No stories found for date: {target_date}")
        return
        
    daily_brief = get_daily_brief_for_date(target_date)
    
    print(f"Generating SEO Blog Post for {target_date} from {len(stories)} stories...")
    blog_content = generate_seo_blog(stories, daily_brief)
    
    if blog_content:
        # Save to file - use frontend public directory for static serving
        # Also try the legacy path
        output_dirs = [
            "/home/team/shared/nichepulse/frontend/public/content/blog",
            "/home/team/shared/site/content/blog",
        ]
        
        saved_paths = []
        for output_dir in output_dirs:
            try:
                os.makedirs(output_dir, exist_ok=True)
                file_path = os.path.join(output_dir, f"{target_date}-daily-intelligence.md")
                with open(file_path, "w") as f:
                    f.write(blog_content)
                saved_paths.append(file_path)
                print(f"SEO Blog Post saved to {file_path}")
            except (OSError, PermissionError) as e:
                print(f"Could not save to {output_dir}: {e}")
        
        # Also save to the ai/output directory
        ai_output_dir = os.path.join(os.path.dirname(__file__), "output")
        os.makedirs(ai_output_dir, exist_ok=True)
        file_path = os.path.join(ai_output_dir, f"blog-{target_date}.md")
        with open(file_path, "w") as f:
            f.write(blog_content)
        print(f"SEO Blog Post saved to {file_path}")
        
        # Archive to database
        try:
            report_id = str(uuid.uuid4())
            content_escaped = blog_content.replace("'", "''")
            metadata = json.dumps({"author": "AI SEO Pipeline", "version": "1.0", "story_count": len(stories)})
            
            # Check if blog already exists for this date
            existing = run_team_db(f"SELECT id FROM reports WHERE date = '{target_date}' AND type = 'blog'")
            if existing:
                # Update existing
                sql = f"UPDATE reports SET content = '{content_escaped}', metadata = '{metadata}' WHERE date = '{target_date}' AND type = 'blog'"
            else:
                # Insert new
                sql = f"INSERT INTO reports (id, date, content, type, metadata) VALUES ('{report_id}', '{target_date}', '{content_escaped}', 'blog', '{metadata}')"
            run_team_db(sql)
            print("SEO Blog Post archived to database.")
        except Exception as e:
            print(f"Failed to archive to database: {e}")
    else:
        print("Failed to generate blog content.")

if __name__ == "__main__":
    main()
