import { useState, useEffect } from 'react'
import axios from 'axios'
import ReactMarkdown from 'react-markdown'
import { X, Sparkles, AlertTriangle, Loader2, Download } from 'lucide-react'

const API_BASE = `/api`

function DeepDiveModal({ isOpen, onClose, story }) {
  const [deepDive, setDeepDive] = useState(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState(null)

  useEffect(() => {
    if (isOpen && story) {
      const fetchDeepDive = async () => {
        try {
          setLoading(true)
          setError(null)
          const res = await axios.get(`${API_BASE}/stories/${story.id}/deep-dive`)
          setDeepDive(res.data)
        } catch (err) {
          console.error('Error fetching deep dive:', err)
          if (err.response && err.response.status === 404) {
            setError('Deep dive report is still being generated by the AI analyst. Please check back in a few minutes.')
          } else {
            setError('Failed to load the deep dive report.')
          }
        } finally {
          setLoading(false)
        }
      }
      fetchDeepDive()
    }
  }, [isOpen, story])

  const downloadDeepDive = () => {
    if (!deepDive) return
    
    const content = `NICHEPULSE PREMIUM DEEP-DIVE\nSector: ${story?.category}\nGenerated at: ${new Date(deepDive.created_at).toLocaleString()}\n\n${deepDive.content}`
    const filename = `NichePulse_DeepDive_${story?.category}_${story?.id.substring(0, 8)}.pdf`
    
    const blob = new Blob([content], { type: 'application/pdf' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = filename
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
  }

  if (!isOpen) return null

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-in fade-in duration-300">
      <div className="bg-white w-full max-w-4xl max-h-[90vh] rounded-2xl shadow-2xl overflow-hidden flex flex-col animate-in zoom-in-95 duration-300">
        {/* Header */}
        <div className="px-6 py-4 border-b border-gray-100 flex justify-between items-center bg-gray-50/50">
          <div className="flex items-center space-x-2">
            <div className="bg-amber-100 p-1.5 rounded-lg">
              <Sparkles className="w-5 h-5 text-amber-600" />
            </div>
            <div>
              <h2 className="text-lg font-display font-bold text-gray-900 leading-tight">Premium Deep-Dive Analysis</h2>
              <p className="text-xs font-medium text-gray-500 uppercase tracking-wider">{story?.category} Sector Update</p>
            </div>
          </div>
          <button 
            onClick={onClose}
            className="p-2 hover:bg-gray-100 rounded-full transition-colors"
          >
            <X className="w-5 h-5 text-gray-400" />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-8">
          {loading ? (
            <div className="flex flex-col items-center justify-center h-64 space-y-4">
              <Loader2 className="w-10 h-10 text-violet-600 animate-spin" />
              <p className="text-gray-500 font-medium">Synthesizing deep-dive intelligence...</p>
            </div>
          ) : error ? (
            <div className="bg-amber-50 border border-amber-200 p-6 rounded-xl text-center">
              <AlertTriangle className="w-12 h-12 text-amber-500 mx-auto mb-4" />
              <h3 className="text-amber-900 font-display font-bold mb-2">Analysis in Progress</h3>
              <p className="text-amber-700 text-sm max-w-md mx-auto">{error}</p>
              <button 
                onClick={onClose}
                className="mt-6 px-6 py-2 bg-amber-600 text-white rounded-lg font-display font-bold text-sm hover:bg-amber-700 transition-colors"
              >
                Close and Return
              </button>
            </div>
          ) : deepDive ? (
            <div className="prose prose-blue max-w-none prose-headings:font-display font-black prose-p:text-gray-600 prose-p:leading-relaxed">
              <ReactMarkdown>{deepDive.content}</ReactMarkdown>
            </div>
          ) : null}
        </div>

        {/* Footer */}
        {deepDive && (
          <div className="px-6 py-4 border-t border-gray-100 bg-gray-50/50 flex justify-between items-center">
            <div className="text-xs text-gray-400 font-medium">
              Generated at: {new Date(deepDive.created_at).toLocaleString()}
            </div>
            <button 
              onClick={downloadDeepDive}
              className="flex items-center space-x-2 px-4 py-2 bg-violet-600 text-white rounded-xl font-display font-bold text-sm hover:bg-violet-700 transition-shadow shadow-md"
            >
              <Download className="w-4 h-4" />
              <span>Download Full Analysis (PDF)</span>
            </button>
          </div>
        )}
      </div>
    </div>
  )
}

export default DeepDiveModal
